name: csanadtest
favicon: null
layout_spectrum: 0.4712861825246364
typography_spectrum: 0.300844595534727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3160660557914525
  lightness: 0.5597904403693974
  saturation: 0.9913068269379437
  rhythmicContrast: 0.337893791962415
purpose: []
